### ISSUE TITLE
First release task list

### ISSUE THREAD

**Issue by nallar** [nallar/Mixin#1]
- [x] Implement source transformations in SourceEditor
- [x] Implement bytecode transformations in ByteCodeEditor
- [x] Implement annotation parsing from source, bytecode and loaded class
- [x] Implement running source/bytecodeeditor using the parsed annotaitons
- [x] Split parsing code to separate project nallar/JavaTransformer
